#!/bin/bash
# $1 = path to black bot
# $2 = path to red bot
# $3 = number of times to play

if [ $# -ne 3 ]
then
	echo Usage: ./test path to black bot, path to red bot, number of times to play
	exit
fi

wins=0

for ((i=0; i < $3; i++))
do
	echo ${i}th game:
	bin/Desdemona $1 $2 2>&1 | grep -A 1 Black
	if (( $? == 0))
	then
		((wins = $wins + 1))
	fi
		
done

echo \# of black wins=$wins
